runmode: debug
addr: :8080
name: aug-blog
url: http://127.0.0.1:8080
max_ping_count: 10
gormlog: true
jwt_ttl: 43200
jwt_secret: 0ep7Q1nRmShGbgJ6udBkGFRGkj7MHgAe
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/augblog.log
  log_format_text: false
  rollingPolicy: daily
  log_rotate_date: 1
  log_rotate_size: 10
  log_backup_count: 7
db:
  name: aug_blog
  addr: 127.0.0.1:3306
  username: root
  password:
  timezone: Asia/Shanghai
  charset: utf8mb4
redis:
  addr: 127.0.0.1:6379
  password:
  db: 0