runmode: debug
addr: :8080
name: aug-blog
url: http://127.0.0.1:8080
max_ping_count: 10
gormlog: true
jwt_ttl: 43200
jwt_secret: 0ep7Q1nRmShGbgJ6udBkGFRGkj7MHgAe
log:
  level: DEBUG
  file_name: log/augblog.log
  max_age: 30
  max_size: 1
  max_backup: 7
  compress: true
db:
  name: aug_blog
  addr: 127.0.0.1:3306
  username: root
  password:
  timezone: Asia/Shanghai
  charset: utf8mb4
redis:
  addr: 127.0.0.1:6379
  password:
  db: 0